python run_tests_safety.py \
        --sut "llama3.2" \
        --judge "llama3.2" \
        --population_size 5 \
        --n_generations 5 \
        --algorithm "nsga2" \
        --max_time "00:00:30" \
        --features_config "configs/safety_features.json"\
        --no_wandb \
        --use_rag \
        --seed 1